# Start with the official RabbitMQ management image
FROM rabbitmq:3.13-management

# Download and enable the Delayed Message Exchange plugin
RUN apt-get update && apt-get install -y curl && \
    curl -L https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.13.0/rabbitmq_delayed_message_exchange-3.13.0.ez -o /opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.13.0.ez && \
    chmod 644 /opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.13.0.ez && \
    rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange && \
    apt-get purge -y --auto-remove curl && \
    rm -rf /var/lib/apt/lists/*
